version: "2.0"
name: "vsphere.post_os_config"

workflows:

    main:
        description: "Post OS configuration"
        type: direct
        input:
            - vm_name
            - requester
        task-defaults:
          on-error:
            - callback_on_error
            - fail
        tasks:
            notify_host_mgmt:
                action: st2.action
                input:
                    ref: core.http
                    parameters:
                        url: "https://pso-tools.cisco.com/cgi-bin/REST/citeis/hostmgmt/{$.vm_name}/scurp/json"
                        headers: "Authorization=Basic Y3BvYWRtOnpeSmY0aWNE"
                        body: "requestor={$.requester}&host={$.vm_name}&size=0&mounts=&location=SJCB&env=prod&purpose=Application%20Server&sox=&level=internal&duty=windows-hosting-duty&requisitionid=1001&db_version=&db_name=&nbu=No&db_disksize=0&db_function=Non-production&os=linux&citeis=Gen2&legacy_postos=1&puppet_tags=&os_version=&join_domain=true"
                        method: POST
                on-success:
                    - post_result
            post_result:
                action: st2.callback
                input:
                    state: "SUCCESS"
                    result: $.body
            callback_on_error:
                action: st2.callback
                input:
                    state: "ERROR"
                    result: $
