---
  name: "post_os_config"
  pack: "vsphere"
  runner_type: "mistral-v2"
  description: "Workflow to configure VM post OS"
  enabled: true
  entry_point: "workflows/post_os_config.yaml"
  parameters: 
    workflow: 
      type: "string"
      default: "vsphere.post_os_config.main"
      immutable: true
    vm_name: 
      type: "string"
      required: true
    requester: 
      type: "string"
      required: true

